apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-tls
  namespace: games
spec:
  secretName: game-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - game.your-domain.com
  duration: 2160h # 90天
  renewBefore: 360h # 15天前更新 